spring.application.name=springboot-crud-with-aws
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=jeevika123

spring.jpa.hibernate.ddl-auto=update
