spring.application.name=springboot-crud-with-aws

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
